import type { ComponentRegistryItem } from "./component-registry.types";

export const componentRegistry = [
  {
    id: "button",
    name: "Button",
    category: "primitive",
    status: "ready",
    description: "Acciones principales, secundarias y estados de carga.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Button/button.usage.md",
  },
  {
    id: "icon-button",
    name: "IconButton",
    category: "primitive",
    status: "ready",
    description: "Boton compacto con icono y etiqueta accesible.",
    importPath: "~/ui",
  },
  {
    id: "input",
    name: "Input",
    category: "primitive",
    status: "ready",
    description: "Campo de texto con variantes line, box y quiet.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Input/input.usage.md",
  },
  {
    id: "date-input",
    name: "DateInput",
    category: "primitive",
    status: "ready",
    description: "Campo base para fechas escolares.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/DateInput/date-input.usage.md",
  },
  {
    id: "field",
    name: "Field",
    category: "primitive",
    status: "ready",
    description: "Etiqueta, requerido, ayuda y error para formularios.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Field/field.usage.md",
  },
  {
    id: "select",
    name: "Select",
    category: "primitive",
    status: "ready",
    description: "Lista cerrada con dropdown visual propio.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Select/select.usage.md",
  },
  {
    id: "checkbox",
    name: "Checkbox",
    category: "primitive",
    status: "ready",
    description: "Seleccion binaria con estados visuales.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Checkbox/checkbox.usage.md",
  },
  {
    id: "radio-group",
    name: "RadioGroup",
    category: "primitive",
    status: "ready",
    description: "Seleccion unica clasica.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/RadioGroup/radio-group.usage.md",
  },
  {
    id: "choice-group",
    name: "ChoiceGroup",
    category: "primitive",
    status: "ready",
    description: "Seleccion unica tipo tira o tarjeta.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/ChoiceGroup/choice-group.usage.md",
  },
  {
    id: "textarea",
    name: "Textarea",
    category: "primitive",
    status: "ready",
    description: "Campo de texto largo.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Textarea/textarea.usage.md",
  },
  {
    id: "badge",
    name: "Badge",
    category: "primitive",
    status: "ready",
    description: "Indicadores breves de estado.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Badge/badge.usage.md",
  },
  {
    id: "panel",
    name: "Panel",
    category: "primitive",
    status: "ready",
    description: "Contenedor de trabajo para contenido relacionado.",
    importPath: "~/ui",
    docsPath: "src/ui/primitives/Panel/panel.usage.md",
  },
  {
    id: "accordion",
    name: "Accordion",
    category: "composed",
    status: "ready",
    description: "Secciones expandibles con animacion suave.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/Accordion/accordion.usage.md",
  },
  {
    id: "search-select",
    name: "SearchSelect",
    category: "composed",
    status: "ready",
    description: "Busqueda con seleccion real desde una lista.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/SearchSelect/search-select.usage.md",
  },
  {
    id: "date-range-input",
    name: "DateRangeInput",
    category: "composed",
    status: "ready",
    description: "Rango de fechas para filtros y reportes.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/DateRangeInput/date-range-input.usage.md",
  },
  {
    id: "tabs",
    name: "Tabs",
    category: "composed",
    status: "ready",
    description: "Pestanas para expedientes y configuraciones.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/Tabs/tabs.usage.md",
  },
  {
    id: "dialog",
    name: "Dialog",
    category: "composed",
    status: "ready",
    description: "Modal para avisos y flujos cortos.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/Dialog/dialog.usage.md",
  },
  {
    id: "dropdown-menu",
    name: "DropdownMenu",
    category: "composed",
    status: "ready",
    description: "Menu compacto para acciones.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/DropdownMenu/dropdown-menu.usage.md",
  },
  {
    id: "toast",
    name: "Toast",
    category: "composed",
    status: "ready",
    description: "Notificacion breve de sistema.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/Toast/toast.usage.md",
  },
  {
    id: "empty-state",
    name: "EmptyState",
    category: "composed",
    status: "ready",
    description: "Estado visual cuando no hay datos.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/EmptyState/empty-state.usage.md",
  },
  {
    id: "skeleton",
    name: "Skeleton",
    category: "composed",
    status: "ready",
    description: "Marcadores visuales de carga.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/Skeleton/skeleton.usage.md",
  },
  {
    id: "tooltip",
    name: "Tooltip",
    category: "composed",
    status: "ready",
    description: "Ayuda breve para controles compactos.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/Tooltip/tooltip.usage.md",
  },
  {
    id: "file-upload",
    name: "FileUpload",
    category: "composed",
    status: "ready",
    description: "Carga visual de documentos y archivos CSV por lote.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/FileUpload/file-upload.usage.md",
  },
  {
    id: "user-menu",
    name: "UserMenu",
    category: "composed",
    status: "ready",
    description: "Menu de usuario con avatar, rol, sesion y acciones.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/UserMenu/user-menu.usage.md",
  },
  {
    id: "notification-center",
    name: "NotificationCenter",
    category: "composed",
    status: "ready",
    description: "Centro de avisos con contador, estados y acciones.",
    importPath: "~/ui",
    docsPath: "src/ui/composed/NotificationCenter/notification-center.usage.md",
  },
  {
    id: "breadcrumbs",
    name: "Breadcrumbs",
    category: "pattern",
    status: "ready",
    description: "Ruta de navegacion para pantallas profundas.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/Breadcrumbs/breadcrumbs.usage.md",
  },
  {
    id: "page-header",
    name: "PageHeader",
    category: "pattern",
    status: "ready",
    description: "Encabezado de pagina con acciones.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/PageHeader/page-header.usage.md",
  },
  {
    id: "data-table",
    name: "DataTable",
    category: "pattern",
    status: "ready",
    description: "Tabla con filtros, seleccion, acciones y paginacion.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/DataTable/data-table.usage.md",
  },
  {
    id: "sidebar",
    name: "Sidebar",
    category: "pattern",
    status: "ready",
    description: "Navegacion lateral principal de producto.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/Sidebar/sidebar.usage.md",
  },
  {
    id: "app-shell",
    name: "AppShell",
    category: "pattern",
    status: "ready",
    description: "Marco de pantalla con sidebar, header, toolbar y contenido.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/AppShell/app-shell.usage.md",
  },
  {
    id: "stat-card",
    name: "StatCard",
    category: "pattern",
    status: "ready",
    description: "Metrica compacta para dashboards.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/StatCard/stat-card.usage.md",
  },
  {
    id: "stepper",
    name: "Stepper",
    category: "pattern",
    status: "ready",
    description: "Progreso visual para procesos largos.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/Stepper/stepper.usage.md",
  },
  {
    id: "confirm-action",
    name: "ConfirmAction",
    category: "pattern",
    status: "ready",
    description: "Confirmacion estandar para acciones delicadas.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/ConfirmAction/confirm-action.usage.md",
  },
  {
    id: "toolbar",
    name: "Toolbar",
    category: "pattern",
    status: "ready",
    description: "Barra operacional para busqueda, filtros y acciones.",
    importPath: "~/ui",
    docsPath: "src/ui/patterns/Toolbar/toolbar.usage.md",
  },
] satisfies ComponentRegistryItem[];
