export type IconIntent =
  | "add"
  | "back"
  | "cancel"
  | "check"
  | "chevron-down"
  | "chevron-left"
  | "chevron-right"
  | "class"
  | "close"
  | "dashboard"
  | "delete"
  | "download"
  | "edit"
  | "empty"
  | "filter"
  | "group"
  | "info"
  | "lock"
  | "login-reset"
  | "logout"
  | "mail"
  | "notifications"
  | "person"
  | "phone"
  | "pin"
  | "print"
  | "refresh"
  | "save"
  | "schedule"
  | "school"
  | "search"
  | "settings"
  | "staff"
  | "student"
  | "success"
  | "teacher"
  | "toggle"
  | "unlock"
  | "upload"
  | "user-settings"
  | "view"
  | "warning";

export type IconContext =
  | "default"
  | "action"
  | "admin"
  | "admission"
  | "danger"
  | "datatable"
  | "form"
  | "navigation"
  | "students"
  | "teachers"
  | "users";

export type IconSize = "xs" | "sm" | "md" | "lg" | "xl" | number;
