import {
  IconAlertTriangle,
  IconArrowLeft,
  IconBarChart,
  IconBook,
  IconBriefcase,
  IconCalendar,
  IconChalkboard,
  IconCheck,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconClipboard,
  IconDashboard,
  IconDownload,
  IconEye,
  IconFilter,
  IconGraduationCap,
  IconHome,
  IconInfo,
  IconLayoutDashboard,
  IconLock,
  IconLogOut,
  IconMail,
  IconMapPin,
  IconPencil,
  IconPhone,
  IconPin,
  IconPlus,
  IconPrinter,
  IconRefresh,
  IconSave,
  IconSearch,
  IconSettings,
  IconToggle,
  IconTrash,
  IconUnlock,
  IconUpload,
  IconUser,
  IconUserCog,
  IconUserPlus,
  IconUsers,
  IconX,
} from "./base-icons";
import type { IconContext, IconIntent } from "./icon-intents";

type IconComponent = typeof IconSearch;

type IconDefinition = {
  default: IconComponent;
  contexts?: Partial<Record<IconContext, IconComponent>>;
};

export const iconMap: Record<IconIntent, IconDefinition> = {
  add: {
    default: IconPlus,
    contexts: {
      admission: IconUserPlus,
      students: IconUserPlus,
      users: IconUserPlus,
    },
  },
  back: { default: IconArrowLeft },
  cancel: { default: IconX },
  check: { default: IconCheck },
  "chevron-down": { default: IconChevronDown },
  "chevron-left": { default: IconChevronLeft },
  "chevron-right": { default: IconChevronRight },
  class: { default: IconChalkboard },
  close: { default: IconX },
  dashboard: {
    default: IconLayoutDashboard,
    contexts: {
      navigation: IconDashboard,
    },
  },
  delete: {
    default: IconTrash,
    contexts: {
      danger: IconTrash,
    },
  },
  download: { default: IconDownload },
  edit: {
    default: IconPencil,
    contexts: {
      datatable: IconPencil,
      form: IconPencil,
    },
  },
  empty: { default: IconInfo },
  filter: { default: IconFilter },
  group: { default: IconUsers },
  info: { default: IconInfo },
  lock: { default: IconLock },
  "login-reset": { default: IconRefresh },
  logout: { default: IconLogOut },
  mail: { default: IconMail },
  person: {
    default: IconUser,
    contexts: {
      students: IconGraduationCap,
      teachers: IconChalkboard,
      users: IconUserCog,
    },
  },
  phone: { default: IconPhone },
  pin: { default: IconPin },
  print: { default: IconPrinter },
  refresh: { default: IconRefresh },
  save: { default: IconSave },
  schedule: { default: IconCalendar },
  school: { default: IconHome },
  search: { default: IconSearch },
  settings: { default: IconSettings },
  staff: { default: IconBriefcase },
  student: { default: IconGraduationCap },
  success: { default: IconCheck },
  teacher: { default: IconChalkboard },
  toggle: { default: IconToggle },
  unlock: { default: IconUnlock },
  upload: { default: IconUpload },
  "user-settings": { default: IconUserCog },
  view: { default: IconEye },
  warning: { default: IconAlertTriangle },
};

export const moduleIconMap = {
  academics: IconBook,
  addresses: IconHome,
  classes: IconChalkboard,
  demographics: IconBarChart,
  enrollment: IconClipboard,
  staff: IconBriefcase,
  students: IconGraduationCap,
  users: IconUserCog,
  zipCodes: IconMapPin,
} satisfies Record<string, IconComponent>;

export const actionLabelIntentMap: Record<string, IconIntent> = {
  "Activar / Desactivar": "toggle",
  "Cambiar estatus": "toggle",
  Desbloquear: "unlock",
  Editar: "edit",
  "Editar alumno": "edit",
  "Editar asignacion": "edit",
  "Editar asignación": "edit",
  "Editar contrato": "edit",
  "Editar perfil academico": "edit",
  "Editar perfil académico": "edit",
  Registrar: "add",
  "Resetear login": "login-reset",
  Ver: "view",
  "Ver alumno": "view",
  "Ver detalle": "view",
};
